### ISSUE TITLE
Review function main()

### ISSUE THREAD

**Issue by AndersonAlencar** [eliasprog/SpacedRepetitionApp#1]
**Arquivo:**
main.swift

**Função**:
main()

**Sugestão de melhora:**
substituir a variável crtl por true: while true { showMenu()
e substituir o case 0: ctrl = false por return

**Comment by helainepontes** [comment]
Ou, o que também é válido, usar o break

**Comment by eliasferreiras** [comment]
A issue foi analisada, validade e já encontra-se implementada na última versão do código.
Muito obrigado!
