### ISSUE TITLE
Sugestao de melhoria

### ISSUE THREAD

**Issue by ronaldogomes96** [eliasprog/SpacedRepetitionApp#2]
Dupla: Bia / Ronaldo
Arquivo: 
main.swift
Descrição: 
Colocar todo o bloco while do menu de opções em uma função separada ou ate em um outro arquivo e so chamar depois, porque ele deixa o main.swift muito longo. Seria interessante separar e deixar esse menu em um local especifico so dele e ficar chamando o que for necessário. Acredito que ajudaria na legibilidade do código :D

**Comment by eliasferreiras** [comment]
Feito, Ronaldo!
Muito obrigado!
