### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by PhoenixPassenger** [eliasprog/SpacedRepetitionApp#3]
Arquivo : CardDAO.swift
Problema encontrado : A chamada`fileManager.homeDirectoryForCurrentUser` só está disponível para o OSX 10.12 ou superior, sendo assim se o script fosse executado em uma versão anterior a essa, o mesmo teria problemas e não seria executado.

Sugestão: Limitar a classe para que só exista caso o OSX seja o correto usando a annotation `@available(OSX 10.12, *)` e colocando o bloco de execução da main dentro da condição `if #available(OSX 10.12, *) {}`

**Comment by eliasferreiras** [comment]
Feito! 
Muito obrigado!
